name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  lint:
    name: Lint shell scripts, markdown, and YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-asdf
      - run: make lint

  validate_apm:
    name: Validate APM packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-asdf
      - run: make compile

  actions_lint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
